config/routes.rb
require_relative '../lib/wiki_gateway'
Rails.application.routes.draw do

  resources :settings
  root 'main#index'

  devise_for :devices
  devise_for :users

  resources :nfc_keys, controller: 'bramnik', path: 'bramnik', only: [:index]
  get 'bramnik/find_user', to: 'bramnik#find_user'
  get 'bramnik/members_statistics', to: 'bramnik#members_statistics'

  resources :projects
  resources :news
  resources :devices, only: [:index, :show]
  resources :users, path: 'hackers', controller: 'hackers', only: [:index, :show, :edit, :update] do
    resources :public_ssh_keys, only: [:create, :destroy]

    member do
      post 'add_mac', to: 'hackers#add_mac'
      delete 'remove_mac', to: 'hackers#remove_mac'
    end

    member do
      post 'add_nfc', to: 'hackers#add_nfc'
      delete 'remove_nfc', to: 'hackers#remove_nfc'
    end

    collection do
      get 'find', to: 'hackers#find_by_mac'
      post 'detected', to: 'hackers#detected_at_hackerspace'
      get 'ssh_keys', to: 'hackers#ssh_keys'
    end
  end
  resources :thanks

  post 'uploader/image', to: 'uploader#image'

  get '/rules', to: 'main#rules'
  get '/calendar', to: 'main#calendar'
  get '/contacts', to: 'main#contacts'
  get '/procedure', to: 'main#procedure'
  get '/board', to: 'main#board'
  get '/tariffs', to: 'main#tariffs'
  get '/howtopay', to: 'main#howtopay'
  get '/chart', to: 'main#chart'
  get '/useful', to: 'hackers#useful'
  get '/profile', to: 'hackers#profile'

  get '/spaceapi', to: 'main#spaceapi', defaults: {format: 'json'}

  authenticate :user do
    mount WikiGateway.new(backend: 'http://localhost:4567/'), at: 'wiki', as: 'wiki_gateway'
  end

  namespace :admin do
    resources :dashboard, only: :index
    resources :users, only: [:new, :create]
    resources :tariffs
    resources :payments
    resources :erip_transactions
    resources :bank_transactions
    post "bank_transactions/mass_update", to: "bank_transactions#mass_update"
    post "erip_transactions/bepaid_notify", to: "erip_transactions#bepaid_notify"
  end

  resources :events, only: [:index] do
    collection do
      get 'add'
    end
  end
end

app/controllers/hackers_controller.rb
class HackersController < ApplicationController
  load_and_authorize_resource :user, parent: false,
                              except: [:useful, :find_by_mac, :detected_at_hackerspace, :ssh_keys]

  def index
    @active_users = ActiveUsersQuery.perform(index_params)
    @non_active_users = User.where.not(id: @active_users.map(&:id))
    respond_to do |format|
      format.html
      format.csv {
                   render csv: User.all,
                   filename: 'hackers',
                   style: can?(:read, NfcKey) ? :with_nfc : :default
                  }
      format.json
    end
  end

  def ssh_keys
    authorize! :ssh_keys, User

    ssh_keys = PublicSshKey.where(user_id: User.allowed.ids).pluck(:body)
    render plain: ssh_keys.map{ |key| key.split(/\s+/, 3)[0..1].join(" ") }.join("\n")
  end

  def show
    @user.generate_tg_auth_token! if @user == current_user
  end

  def profile
    redirect_to current_user
  end

  def find_by_mac
    authorize! :find_by_mac, User
    set_hacker_by_mac

    if @hacker.nil?
      render json: {}, status: :not_found
    else
      render json: @hacker, status: :ok
    end
  end

  def detected_at_hackerspace
    authorize! :detected_at_hackerspace, User
    set_hacker_by_mac

    if @hacker.nil?
      render json: {}, status: :not_found
    else
      @hacker.update(last_seen_in_hackerspace: Time.now)
      render json: @hacker, status: :ok
    end
  end

  def add_mac
    if params[:mac].present? and params[:mac][/^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$/].present?
      @user.macs << Mac.create(address: params[:mac]&.downcase)
      redirect_to edit_user_path(@user)
    else
      redirect_to edit_user_path(@user), alert: 'Ошибка формата mac адреса'
    end
  end

  def remove_mac
    Mac.find(params[:mac_id])&.destroy
    redirect_to edit_user_path(@user)
  end

  def add_nfc
    @nfc_key = NfcKey.new(body: params[:nfc]&.downcase, user: @user)

    if @nfc_key.save
      redirect_to edit_user_path(@user)
    else
      redirect_to edit_user_path(@user),
        alert: "Ошибка сохранения NFC ключа: #{@nfc_key.errors.full_messages.join("\n")}"
    end
  end

  def remove_nfc
    key = @user.nfc_keys.find_by(body: params[:nfc]&.downcase)
    key&.destroy
    redirect_to edit_user_path(@user)
  end

  def edit
    @new_public_ssh_key = PublicSshKey.new(user: @user)
    redirect_to root_path, alert: 'Ошибка' unless @user == current_user or current_user.admin?
  end

  def useful
    authorize! :useful, User
    @page_content =
        if Rails.env.production?
          Net::HTTP.get(URI.parse('https://raw.githubusercontent.com/minsk-hackerspace/hackerspace.by/master/app/views/hackers/useful.md'))
        else
          File.read(Rails.root.join('app', 'views', 'hackers', 'useful.md'))
        end
  end

  def update
    @user.updating_by = current_user

    if @user.update(user_params)
      flash[:notice] = 'Профиль изменен'
      flash[:alert] = @user.errors.full_messages.join "\n"
      redirect_to users_path
    else
      render :edit
    end
  end

  private

  def set_hacker
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :email,
      :hacker_comment,
      :photo,
      :first_name,
      :last_name,
      :telegram_username,
      :alice_greeting,
      :account_banned,
      :monthly_payment_amount,
      :github_username,
      :is_learner,
      :project_id,
      :guarantor1_id,
      :guarantor2_id,
      :tariff_id
    )
  end

  def index_params
    params.slice(:order)
  end

  def set_hacker_by_mac
    @hacker = Mac.find_by(address: params[:mac]&.downcase).try(&:user)
  end
end

app/helpers/hackers_helper.rb
module HackersHelper
  def row_class(hacker)
    return if hacker.inactive?

    if hacker.last_payment.present? && hacker.last_payment.end_date < Time.now.to_date
      return hacker.is_learner? ? 'info' : 'danger'
    end

    'warning'
  end
end

app/views/hackers/_form.html.haml
.row
  .col-lg-6
    = form_for @user, :html => { :multipart => true } do |f|
      - if @user.errors.any?
        #error_explanation
          %h2= "#{pluralize(@user.errors.count, "error")} сохранить не получится:"
          %ul
            - @user.errors.full_messages.each do |msg|
              %li= msg

      .form-group.mandatory
        = f.label :email, 'Email'
        = f.text_field :email, class: 'form-control'
      .form-group
        = f.label :first_name, 'Имя'
        = f.text_field :first_name, class: 'form-control'
      .form-group
        = f.label :last_name, 'Фамилия'
        = f.text_field :last_name, class: 'form-control'
      .form-group
        = f.label :hacker_comment, 'Примечание'
        = f.text_area :hacker_comment, rows: 2, class: 'form-control'
      .form-group.mandatory
        = f.label :photo, 'Изображение, до 3 МБ'
        = f.file_field :photo

      .form-group
        = f.label 'Рекомендатели:'
        %br
        - users = User.select(:id, :first_name, :last_name).order(:id).all
        = f.collection_select :guarantor1_id, users, :id, :full_name_with_id, {include_blank: true}, class: 'form-select'
        = f.collection_select :guarantor2_id, users, :id, :full_name_with_id, {include_blank: true}, class: 'form-select'

      .form-group
        = f.label 'Никнейм в Telegram'
        = f.text_field :telegram_username, class: 'form-control', value: @user.telegram_username

      .form-group
        = f.label 'Приветствие для Алисы'
        = f.text_field :alice_greeting, class: 'form-control', value: @user.alice_greeting

      .form-group
        = f.label 'Никнейм в Github'
        = f.text_field :github_username, class: 'form-control', value: @user.github_username

      .form-group
        = f.label :tariff
        - unless current_user.admin?
          %br= "Изменение тарифа возможно 1 раз в #{Tariff::CHANGE_LIMIT_IN_DAYS} дней"
          - if current_user.able_to_change_tariff_now?
            Доступно
          - else
            Доступно после
            = current_user.tariff_changeble_date.strftime('%d/%m/%Y %H:%M')
        = f.collection_select :tariff_id, Tariff.available_by(current_user), :id, :name_with_price, {}, class: 'form-select', disabled: !current_user.able_to_change_tariff_now?

      - if current_user.admin?
        .form-group
          = f.check_box :is_learner, class: 'form-check-input', value: @user.is_learner
          = f.label 'Курсант'

        .form-group
          = f.label 'Проект'
          = f.select :project_id, Project.all.map{|p| [p.name, p.id]}, {include_blank: true}, class: 'form-select', value: @user.project_id

        .row
          .col-lg-3
            .form-group
              = f.label 'Banned'
              = f.check_box :account_banned, class: 'form-check-input', value: @user.account_banned

      .form-group
        = f.submit 'Сохранить', class: 'btn btn-primary'

-#MAC
%hr
.row
  .col-lg-6
    - unless @user.macs.empty?
      %h3 Мак адреса пользователя
      - @user.macs.each do |mac|
        .row
          .col-lg-4
            %p
              = mac.address
          .col-lg-1
            %p
              = link_to 'Удалить', remove_mac_user_path(@user, mac_id: mac.id), method: :delete, data: { confirm: 'Are you sure?' }
.row
  .col-lg-6
    = form_tag("/hackers/#{@user.id}/add_mac") do
      .form-group
        = text_field_tag(:mac, nil, class: 'form-control')
      .form-group
        = submit_tag('Добавить Mac адрес', class: 'btn btn-primary')

-#NFC
%hr
.row
  .col-lg-6
    - unless @user.nfc_keys.empty?
      %h3 NFC ключи пользователя
      - @user.nfc_keys.each do |nfc|
        .row.small
          .col-lg-4
            %p
              = nfc.body
          .col-lg-1
            %p
              = link_to 'Удалить', remove_nfc_user_path(@user, nfc: nfc.body), method: :delete
.row
  .col-lg-6
    = form_tag("/hackers/#{@user.id}/add_nfc") do
      .form-group
        = text_field_tag(:nfc, nil, class: 'form-control')
      .form-group
        = submit_tag('Добавить NFC ключ', class: 'btn btn-primary')

-# Public SSH Keys
%hr
.row
  .col-lg-6
    - if @user.public_ssh_keys.any?
      %h3 Public SSH ключи пользователя
      - @user.public_ssh_keys.each do |public_ssh_key|
        .row.small
          .col-lg-10
            %p{:title => public_ssh_key.body}
              = public_ssh_key.body[0..20] + "..." + public_ssh_key.body[-30..-1]
          .col-lg-1
            %p
              = link_to 'Удалить', user_public_ssh_key_path(@user, public_ssh_key), method: :delete, data: { confirm: 'Are you sure?' }
.row
  .col-lg-6
    = form_for [@user, @new_public_ssh_key] do |f|
      = f.hidden_field :user_id
      .form-group
        = f.text_area :body, class: 'form-control'
      .form-group
        = submit_tag('Добавить публичный SSH ключ', class: 'btn btn-primary')

app/views/hackers/_hacker.html.haml
%td= image_tag hacker.avatar_url(:thumb)
%td= hacker.id
%td= hacker.email
%td= "#{hacker.first_name} #{hacker.last_name}"
%td= simple_format hacker.hacker_comment
%td= hacker.paid_until&.to_formatted_s(:long)
%td= hacker.tariff&.name
%td= hacker.tariff&.monthly_price
%td
  = link_to hacker.telegram_username, "https://t.me/" + hacker.telegram_username if hacker.telegram_username
%td= link_to image_tag('info_32x32.png', class: 'no-shadow'), user_path(hacker)
%td
  - if can?(:edit, hacker)
    = link_to image_tag('edit_gear_icon.png', class: 'no-shadow'), edit_user_path(hacker)

app/views/hackers/_hackers.html.haml
%table.table.hackers-list
  %thead
    %th
    %th Номер
    %th= t('users.email')
    %th= t('users.first_name')
    %th= t('users.comment')
    %th= t('users.last_payment_ended_at')
    %th Тариф
    %th BYN/мес.
    %th= t('users.telegram_username')
    %th
    %th
  %tbody
    - hackers.each do |hacker|
      %tr{class: row_class(hacker)}
        = render 'hacker', hacker: hacker

app/views/hackers/_payments.html.haml
.row.small
  .col-md-10
    %h3= t('users.payments.title')
    %p= t('users.payments.title') + ": #{@user.monthly_payment_amount} " + t('users.payments.rate')

    %table.table
      %thead
        %th= t('users.payments.date')
        %th= t('users.payments.amount')
        %th= t('users.payments.start_date')
        %th= t('users.payments.end_date')
      %tbody
        - payments.each do |payment|
          %tr
            %td= payment.paid_at
            %td= payment.amount
            %td= payment.start_date
            %td= payment.end_date

app/views/hackers/_projects.html.haml
- if projects.any?
  .row.small
    .col-md-10
      %h3= t('users.projects.title')
      - projects.each do |project|
        %ul
          %li
            = link_to project.name, project_path(project)

app/views/hackers/edit.html.haml
%h1= @user.email


= render 'form'
%hr

= link_to 'Назад к списку ', users_path, class: 'btn btn-info btn-sm'

app/views/hackers/index.html.haml
%h2= t('users.title')

.filters.pull-right
  .dropdown
    %button#sort_hackers.btn.dropdown-toggle{type: "button", "aria-expanded" => "false", "aria-haspopup" => "true", "data-bs-toggle" => "dropdown", :href => "#"}
      = t('users.order.title')
    %ul.dropdown-menu.dropdown-menu-right{"aria-labelledby" => "sort_hackers"}
      %li= link_to t('users.order.id'), users_path, class: "dropdown-item"
      %li= link_to t('users.order.payments'), users_path(order: 'payments'), class: "dropdown-item"
      %li= link_to t('users.order.last_seen'), users_path(order: 'last_seen'), class: "dropdown-item"
      %li= link_to t('users.order.course'), users_path(order: 'course'), class: "dropdown-item"

.row
  .col-lg-12
    = render 'hackers', hackers: @active_users

%h4 Suspended, banned and forgotten
.row
  .col-lg-12
    = render 'hackers', hackers: @non_active_users

app/views/hackers/show.html.haml
.row.mb-5
  .col-md-8
    = link_to t('common.back'), users_path, class: 'btn btn-primary'
    - if can?(:edit, @user)
      = link_to t('common.edit'), edit_user_path(@user), class: 'btn btn-primary'

.row
  .col-md-4
    = image_tag @user.avatar_url(:medium)
    %p
      = @user.hacker_comment
    %p.small
      = t('users.last_sign_in_at')
      = @user.last_sign_in_at

    - if @user == current_user
      %p
        = link_to "Авторизоваться у Брамника",
          "https://t.me/#{Setting['bramnikBotName']}?start=#{@user.tg_auth_token}", class: "btn btn-secondary"

  .col-md-8
    %p
      %strong= t('users.email') + ':'
      = @user.email
      - if @user.is_learner?
        %strong
          (
          = t('users.learner')
          )
    %p
      %strong= t('users.personal_number') + ':'
      = @user.id
    - if @user.first_name.present?
      %p
        %strong= t('users.first_name') + ':'
        = @user.first_name
    - if @user.last_name.present?
      %p
        %strong= t('users.last_name') + ':'
        = @user.last_name

    %p
      %strong Тариф:
      = @user.tariff&.name_with_price

    - if @user.guarantor1.present?
      %p
        %strong= t('users.guarantor1') + ':'
        = @user.guarantor1.full_name

    - if @user.guarantor2.present?
      %p
        %strong= t('users.guarantor2') + ':'
        = @user.guarantor2.full_name

    - if @user.telegram_username.present?
      %p
        %strong= t('users.telegram_username') + ':'
        %a{href: 'https://t.me/' + @user.telegram_username, target: '_blank'}
          = @user.telegram_username
    - if @user.github_username.present?
      %p
        %strong= t('users.github_username') + ':'
        %a{href: 'https://github.com/' + @user.github_username, target: '_blank'}
          = @user.github_username

= render 'projects', projects: @user.projects

= render 'payments', payments: @user.payments.order(paid_at: :desc)

-if @user.public_ssh_keys.any?
  .row.additional_info
    .col-md-8
      %h4= t('users.public_ssh_keys') + ':'
      - @user.public_ssh_keys.each do |public_ssh_key|
        .ssh-public-key= public_ssh_key.body