config/routes.rb
require_relative '../lib/wiki_gateway'
Rails.application.routes.draw do

  resources :settings
  root 'main#index'

  devise_for :devices
  devise_for :users

  resources :nfc_keys, controller: 'bramnik', path: 'bramnik', only: [:index]
  get 'bramnik/find_user', to: 'bramnik#find_user'
  get 'bramnik/members_statistics', to: 'bramnik#members_statistics'

  resources :projects
  resources :news
  resources :devices, only: [:index, :show]
  resources :users, path: 'hackers', controller: 'hackers', only: [:index, :show, :edit, :update] do
    resources :public_ssh_keys, only: [:create, :destroy]

    member do
      post 'add_mac', to: 'hackers#add_mac'
      delete 'remove_mac', to: 'hackers#remove_mac'
    end

    member do
      post 'add_nfc', to: 'hackers#add_nfc'
      delete 'remove_nfc', to: 'hackers#remove_nfc'
    end

    collection do
      get 'find', to: 'hackers#find_by_mac'
      post 'detected', to: 'hackers#detected_at_hackerspace'
      get 'ssh_keys', to: 'hackers#ssh_keys'
    end
  end
  resources :thanks

  post 'uploader/image', to: 'uploader#image'

  get '/rules', to: 'main#rules'
  get '/calendar', to: 'main#calendar'
  get '/contacts', to: 'main#contacts'
  get '/procedure', to: 'main#procedure'
  get '/board', to: 'main#board'
  get '/tariffs', to: 'main#tariffs'
  get '/howtopay', to: 'main#howtopay'
  get '/chart', to: 'main#chart'
  get '/useful', to: 'hackers#useful'
  get '/profile', to: 'hackers#profile'

  get '/spaceapi', to: 'main#spaceapi', defaults: {format: 'json'}

  authenticate :user do
    mount WikiGateway.new(backend: 'http://localhost:4567/'), at: 'wiki', as: 'wiki_gateway'
  end

  namespace :admin do
    resources :dashboard, only: :index
    resources :users, only: [:new, :create]
    resources :tariffs
    resources :payments
    resources :erip_transactions
    resources :bank_transactions
    post "bank_transactions/mass_update", to: "bank_transactions#mass_update"
    post "erip_transactions/bepaid_notify", to: "erip_transactions#bepaid_notify"
  end

  resources :events, only: [:index] do
    collection do
      get 'add'
    end
  end
end

app/models/setting.rb
# == Schema Information
#
# Table name: settings
#
#  id          :integer          not null, primary key
#  key         :string           not null
#  value       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  description :string
#
# Indexes
#
#  index_settings_on_key  (key)
#

class Setting < ApplicationRecord

  validates :key, presence: true, uniqueness: true

  def self.[](key)
    s = Setting.where(key: key).first
    return nil if s.nil?
    s.value
  end

  def self.[]=(key, value)
    s = Setting.where(key: key).first
    s = Setting.new(key: key) if s.nil?
    s.value = value
    s.save
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
#  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @settings = Setting.all
  end

  def show
  end

  def new
    @setting = Setting.new
  end

  def edit
  end

  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to settings_url, notice: 'Setting was successfully created.' }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to settings_url, notice: 'Setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_url, notice: 'Setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:key, :value)
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.haml
= form_for @setting do |f|
  - if @setting.errors.any?
    #error_explanation
      %h2= "#{pluralize(@setting.errors.count, "error")} prohibited this setting from being saved:"
      %ul
        - @setting.errors.full_messages.each do |msg|
          %li= msg
  .form-group.mandatory
    = f.label :key
    = f.text_field :key
  .form-group.mandatory
    = f.label :value
    = f.text_field :value

  .actions
    = f.submit 'Save'

app/views/settings/edit.html.haml
%h1 Editing setting

= render 'form'

= link_to 'Back', settings_path

app/views/settings/index.html.haml
%h1
  = t(".title")

.container
  %table.table
    %thead
      %tr
        %th= Setting.human_attribute_name(:key)
        %th= Setting.human_attribute_name(:value)
        %th= Setting.human_attribute_name(:description)
        %th

    %tbody
      - @settings.each do |setting|
        %tr
          %td= setting.key
          %td= setting.value
          %td= setting.description
          %td= link_to 'Edit', edit_setting_path(setting)

%br

= link_to 'New Setting', new_setting_path

app/views/settings/new.html.haml
%h1 New setting

= render 'form'

= link_to 'Back', settings_path

app/views/settings/show.html.haml
%p#notice= notice

%p
  %b= @setting.key
  = ':'
  = @setting.value

= link_to 'Edit', edit_setting_path(@setting)
\|
= link_to 'Back', settings_path