config/routes.rb
require_relative '../lib/wiki_gateway'
Rails.application.routes.draw do

  resources :settings
  root 'main#index'

  devise_for :devices
  devise_for :users

  resources :nfc_keys, controller: 'bramnik', path: 'bramnik', only: [:index]
  get 'bramnik/find_user', to: 'bramnik#find_user'
  get 'bramnik/members_statistics', to: 'bramnik#members_statistics'

  resources :projects
  resources :news
  resources :devices, only: [:index, :show]
  resources :users, path: 'hackers', controller: 'hackers', only: [:index, :show, :edit, :update] do
    resources :public_ssh_keys, only: [:create, :destroy]

    member do
      post 'add_mac', to: 'hackers#add_mac'
      delete 'remove_mac', to: 'hackers#remove_mac'
    end

    member do
      post 'add_nfc', to: 'hackers#add_nfc'
      delete 'remove_nfc', to: 'hackers#remove_nfc'
    end

    collection do
      get 'find', to: 'hackers#find_by_mac'
      post 'detected', to: 'hackers#detected_at_hackerspace'
      get 'ssh_keys', to: 'hackers#ssh_keys'
    end
  end
  resources :thanks

  post 'uploader/image', to: 'uploader#image'

  get '/rules', to: 'main#rules'
  get '/calendar', to: 'main#calendar'
  get '/contacts', to: 'main#contacts'
  get '/procedure', to: 'main#procedure'
  get '/board', to: 'main#board'
  get '/tariffs', to: 'main#tariffs'
  get '/howtopay', to: 'main#howtopay'
  get '/chart', to: 'main#chart'
  get '/useful', to: 'hackers#useful'
  get '/profile', to: 'hackers#profile'

  get '/spaceapi', to: 'main#spaceapi', defaults: {format: 'json'}

  authenticate :user do
    mount WikiGateway.new(backend: 'http://localhost:4567/'), at: 'wiki', as: 'wiki_gateway'
  end

  namespace :admin do
    resources :dashboard, only: :index
    resources :users, only: [:new, :create]
    resources :tariffs
    resources :payments
    resources :erip_transactions
    resources :bank_transactions
    post "bank_transactions/mass_update", to: "bank_transactions#mass_update"
    post "erip_transactions/bepaid_notify", to: "erip_transactions#bepaid_notify"
  end

  resources :events, only: [:index] do
    collection do
      get 'add'
    end
  end
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id                 :integer          not null, primary key
#  name               :string
#  short_desc         :text
#  full_desc          :text
#  image              :string
#  created_at         :datetime
#  updated_at         :datetime
#  photo_file_name    :string
#  photo_content_type :string
#  photo_file_size    :integer
#  photo_updated_at   :datetime
#  user_id            :integer
#  markup_type        :string           default("html")
#  public             :boolean          default(FALSE)
#  project_status     :string           default("активный")
#
# Indexes
#
#  index_projects_on_user_id  (user_id)
#

class Project < ApplicationRecord

  SUPPORTED_MARKUPS = %w(html markdown)

  belongs_to :user
  has_many :payments

  has_attached_file :photo,
                    styles: {
                      original: '600x600>',
                      medium: '400x400#',
                      thumb: '200x200>'
                    },
                    default_url: 'default.png'

  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
  validates_attachment :photo, presence: true
  #, size: { in: 0..3.megabytes }


  validates :name, uniqueness: true
  validates :name, :short_desc, :project_status, presence: true
  validates :markup_type, inclusion: SUPPORTED_MARKUPS
  scope :published, -> { where public: true }

  def name_with_id
    "#{self.id}. #{self.name}"
  end

  def payments_sum
    payments.sum(:amount)
  end
end

app/controllers/projects_controller.rb
#encoding: utf-8
require 'sanitize'

class ProjectsController < ApplicationController
#  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create]
  load_and_authorize_resource
  before_action :set_project, only: [:edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.order(updated_at: :desc).all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    @payments = @project.payments.includes(:user)
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Проект создан.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Проект изменен.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Проект удален.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      permitted_attrs = [:name, :short_desc, :full_desc, :photo, :markup_type, :project_status]
      permitted_attrs << :public if @project.present? && @project.user == current_user

      result_params = params.require(:project).permit(permitted_attrs)
      sanitize_config = Sanitize::Config.merge(Sanitize::Config::RELAXED,
        :elements        => Sanitize::Config::RELAXED[:elements] + ['iframe'],
        :attributes      => Sanitize::Config::RELAXED[:attributes].merge({
          'iframe' => %w(width height src frameborder allow allowfullscreen)
        }),
        :remove_contents => true
      )
      result_params[:short_desc] = Sanitize.fragment(result_params[:short_desc], sanitize_config)
      result_params[:full_desc] = Sanitize.fragment(result_params[:full_desc], sanitize_config)
      result_params
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= form_for @project, :html => { :multipart => true } do |f|
  - if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} сохранить не получится:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  .form-group.mandatory
    = f.label 'Название'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :public
    = f.check_box :public
  .form-group
    = f.label 'Текущее состояние проекта'
    = f.text_field :project_status, class: 'form-control'
  .row
    .form-group.col-lg-2
      = f.label 'Тип разметки текста'
      = f.collection_select :markup_type, Project::SUPPORTED_MARKUPS, :to_s, :to_s, {}, class: 'form-control'
  .form-group{:class => 'mandatory'}
    = f.label 'Краткое описание'
    = f.text_area :short_desc, rows: 5, class: 'form-control'
  .form-group
    = f.label 'Полное описание'
    = f.text_area :full_desc, class: 'form-control tinymce', rows: 40, cols: 120
    = javascript_tag {tinymce_configurations_javascript}
  .form-group.mandatory
    = f.label 'Изображение, до 3 МБ'
    = f.file_field :photo

  .form-group
    = f.submit 'Сохранить', class: 'btn btn-primary'

app/views/projects/edit.html.haml
%h1 Редактирование

= render 'form'

= link_to 'Назад к списку проектов', projects_path, class: 'btn btn-info btn-sm'

= link_to 'Удалить', project_path(@project), class: 'btn btn-danger btn-sm', data: { confirm: "Точно?" }, method: :delete

%br{:class => "bottom_margin"}

app/views/projects/index.html.haml
%h1 Наши проекты

- @projects.each_slice(2) do |project_row|
  .row.mb-5
    - project_row.each do |project|
      .col-lg-6
        %h2
          = link_to project.name_with_id, project_path(project)
        %p
          = link_to image_tag(project.photo.url(:medium), class: 'left-block img-fluid'), project_path(project)
        %p
          %em
            Статус:
            = project.project_status
        %p
          = project.short_desc.html_safe
        %p
          = link_to "Подробнее >>>", project_path(project)

- if user_signed_in?
  = link_to 'Добавить проект', new_project_path, class: 'btn btn-info'

app/views/projects/new.html.haml
%h1 Новый проект

= render 'form'

= link_to 'Назад к списку проектов', projects_path, class: 'btn btn-info btn-sm'

app/views/projects/show.html.haml
.row
  %h1
    = @project.name_with_id
.row
  %h3
    = "Статус: #{@project.project_status}"
  .lead
    = markup2html @project.short_desc, @project.markup_type
    =image_tag @project.photo.url(:original), class: 'center-block img-fluid'

.row
  = markup2html @project.full_desc, @project.markup_type

.row
  .d-grid.gap-2.d-md-flex.justify-content-md-end
    = link_to 'Назад', projects_path, class: 'btn btn-primary me-md-2'
    -if can? :update, @project
      = link_to 'Изменить', edit_project_path(@project), class: 'btn btn-secondary'

.row
  %h3
    = "Собрано денег: #{@project.payments_sum} BYN"

  - if user_signed_in?
    .col-md-12
      - @payments.each do |payment|
        .row
          .col-md-1
            = link_to_if current_user.admin?, payment.amount, admin_payment_path(payment)
          .col-md-3
            - if payment.user.present?
              = link_to_if current_user.admin?, payment.user.email, user_path(payment.user)
          .col-md-2
            = payment.paid_at.strftime('%d-%m-%Y %H:%M')
.row
  %p

#disqus_thread
:javascript
  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
  var disqus_shortname = 'hackerspaceby'; // Required - Replace '' with your forum shortname

  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function() {
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
%noscript
  Please enable JavaScript to view the
  %a{:href => "https://disqus.com/?ref_noscript"} comments powered by Disqus.